### ISSUE TITLE
TimeGraphRow has field entryId that is filled as entryID

### ISSUE THREAD

**Issue by tahini** [theia-ide/tsp-typescript-client#3]
Consumers of the TimeGraphRow, like tsp-data-provider.ts in theia-trace-extension must do this: (row as any).entryID to get the entryId, which gives lint errors as any types should be avoided. The client should be updated instead

**Comment by tahini** [comment]
Actually, it seems a lot of classes' fields defined in the TspClient do not correspond to the values described in the trace server protocol: https://github.com/theia-ide/trace-server-protocol/blob/master/API.yaml

For instance, the state from the TspClient has a startTime and duration, while the TSP plans for start/end.

IIUC, these values should match perfectly, right? So both TspClient and trace server should be updated

**Comment by tahini** [comment]
Thank eslint for highlighting this ;-)

**Comment by bhufmann** [comment]
Yes, we need to align the TSP, server and client implementation

**Comment by tahini** [comment]
I'll start fixing this. Do we take the trace-server-protocol as the source of truth for this and fix the rest?

**Comment by bhufmann** [comment]
> I'll start fixing this. Do we take the trace-server-protocol as the source of truth for this and fix the rest?

The code should reflect what the TSP defines. However, if a name doesn't fit or is not consistent, you can update the TSP as well and then align the code implementation.

**Comment by tahini** [comment]
First steps for fixing this:

Fix the trace server protocol: https://github.com/theia-ide/trace-server-protocol/pull/27

Make the trace server behave according to the spec: https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/167256
