### ISSUE TITLE
Responses with no body cause uncaught exception

### ISSUE THREAD

**Issue by bhufmann** [theia-ide/tsp-typescript-client#6]
If  a server returns a request with no body, the call to response.json() will cause an uncaught exception: "Uncaught SyntaxError: Unexpected end of JSON input".

The line `const json = await response.json() as T;` in method `performRequest()` of rest-client.ts causes the exception.

**Comment by PatrickTasse** [comment]
Fixed with https://github.com/theia-ide/tsp-typescript-client/pull/15
